# Generated by Django 6.0.6 on 2026-07-02 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('engagement_estimation', models.FloatField(default=0.0)),
                ('actual_engagement', models.FloatField(default=0.0)),
                ('predicted_engagement', models.FloatField(default=0.0)),
                ('predicted_reading_estimation', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.experimentcondition'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('participant_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('experiment_phase', models.CharField(choices=[('chat_1', 'Chat 1'), ('survey_1', 'Survey 1'), ('chat_2', 'Chat 2'), ('survey_2', 'Survey 2'), ('completed', 'Completed')], default='chat_1', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_condition_participants', to='chatbot.experimentcondition')),
                ('first_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_condition_participants', to='chatbot.experimentcondition')),
                ('second_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_condition_participants', to='chatbot.experimentcondition')),
            ],
            options={
                'ordering': ['participant_number'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chatbot.participant'),
        ),
    ]
