# Generated by Django 6.0.6 on 2026-06-17 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='title',
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.experimentcondition')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chatbot.participant'),
        ),
    ]
