# Generated by Django 6.0.6 on 2026-07-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_participant_chat_1_finished_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('interaction_order', models.IntegerField()),
                ('final_research_question', models.TextField()),
                ('cluster_count', models.IntegerField(default=0)),
                ('mean_ideas_per_cluster', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.experimentcondition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.participant')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_number', models.IntegerField()),
                ('cluster_name', models.CharField(max_length=255)),
                ('idea_count', models.IntegerField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='chatbot.conversationanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_text', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='chatbot.ideacluster')),
            ],
        ),
    ]
