# Generated by Django 6.0.6 on 2026-06-17 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatsession_title_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='post_survey_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='pre_survey_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='assigned_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chatbot.experimentcondition'),
        ),
    ]
