# Generated by Django 6.0.6 on 2026-06-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_participant_post_survey_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
    ]
