# Generated by Django 6.0.6 on 2026-07-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversationanalysis_ideacluster_clusteridea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='agent_condition',
        ),
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='session',
        ),
        migrations.RemoveField(
            model_name='ideacluster',
            name='analysis',
        ),
        migrations.DeleteModel(
            name='ClusterIdea',
        ),
        migrations.DeleteModel(
            name='ConversationAnalysis',
        ),
        migrations.DeleteModel(
            name='IdeaCluster',
        ),
    ]
