# Generated by Django 6.0.6 on 2026-06-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatsession_total_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response_time_ms',
            field=models.IntegerField(default=0),
        ),
    ]
