# Generated by Django 6.0.6 on 2026-08-23 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_conversationanalysis_agent_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('interaction_order', models.IntegerField()),
                ('final_research_question', models.TextField()),
                ('cluster_count', models.IntegerField(default=0)),
                ('mean_ideas_per_cluster', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.experimentcondition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.participant')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_order', models.IntegerField()),
                ('idea_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.experimentcondition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_ideas', to='chatbot.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_ideas', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_number', models.IntegerField()),
                ('cluster_name', models.CharField(max_length=255)),
                ('cluster_reason', models.TextField(blank=True, default='')),
                ('idea_count', models.IntegerField(default=0)),
                ('human_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='chatbot.conversationanalysis')),
            ],
            options={
                'ordering': ['cluster_number'],
            },
        ),
        migrations.CreateModel(
            name='ClusterIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_text', models.TextField()),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('extracted_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_memberships', to='chatbot.extractedidea')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='chatbot.ideacluster')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ideacluster',
            constraint=models.UniqueConstraint(fields=('analysis', 'cluster_number'), name='unique_cluster_number_per_analysis'),
        ),
    ]
