# Generated by Django 6.0.6 on 2026-06-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chatmessage_response_time_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='engagement_estimation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='predicted_engagement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='predicted_reading_estimation',
            field=models.FloatField(default=0.0),
        ),
    ]
