# Generated by Django 6.0.6 on 2026-06-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chatmessage_engagement_estimation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='actual_engagement',
            field=models.FloatField(default=0.0),
        ),
    ]
